export const ITIL_PRACTICE_GROUPS = [
    {
        name: "Prácticas de gestión general",
        practices: [
            "Gestión de la arquitectura",
            "Mejora continua",
            "Gestión de la seguridad de la información",
            "Gestión del conocimiento",
            "Medición y reporte",
            "Gestión del cambio organizacional",
            "Gestión del portafolio",
            "Gestión de proyectos",
            "Gestión de las relaciones",
            "Gestión de riesgos",
            "Gestión financiera de servicios",
            "Gestión de la estrategia",
            "Gestión de proveedores",
            "Gestión de la fuerza laboral y el talento",
        ],
    },
    {
        name: "Prácticas de gestión de servicios",
        practices: [
            "Gestión de la disponibilidad",
            "Análisis de negocio",
            "Gestión de la capacidad y el rendimiento",
            "Habilitación del cambio",
            "Gestión de incidentes",
            "Gestión de activos de TI",
            "Monitorización y gestión de eventos",
            "Gestión de problemas",
            "Gestión de liberaciones",
            "Gestión del catálogo de servicios",
            "Gestión de la configuración del servicio",
            "Gestión de la continuidad del servicio",
            "Diseño del servicio",
            "Centro de servicios al usuario",
            "Gestión de niveles de servicio",
            "Gestión de solicitudes de servicio",
            "Validación y pruebas del servicio",
        ],
    },
    {
        name: "Prácticas de gestión técnica",
        practices: [
            "Gestión del despliegue",
            "Gestión de infraestructura y plataformas",
            "Desarrollo y gestión de software",
        ],
    },
];
